rly_file = "XmasTree.rly"
ttb_files = [ "Xmas_Tree.ttb",]
ssn_files = [ "XmasTree.ssn",]
img_files = [ "XmasTree.bmp",]
doc_files = [ "README.md",]
release_date = "2026-07-22"
version = "1.0.0"
country_code = "FN"
factual = false
description = ""
year = 2026
display_name = "Xmastree"
name = "Xmastree"
signal_position = "left"
author = "Kristian Zarębski"
contributors = []
